// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALGE5j_Q0N0pn2MkZ04K5nqhj2IyrgNwI',
    appId: '1:780065756554:android:cc4b24850906180bace473',
    messagingSenderId: '780065756554',
    projectId: 'dd-app-eb798',
    storageBucket: 'dd-app-eb798.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMd-RtinvrFDvV47J8NB8gQgWGLEGS-UI',
    appId: '1:780065756554:ios:3cd2b0315886c231ace473',
    messagingSenderId: '780065756554',
    projectId: 'dd-app-eb798',
    storageBucket: 'dd-app-eb798.appspot.com',
    androidClientId: '780065756554-6e433favls1r59r9cafuq19c3dgic78i.apps.googleusercontent.com',
    iosClientId: '780065756554-429bjhmp09dkaik63oo494sacjbh9j34.apps.googleusercontent.com',
    iosBundleId: 'com.example.dd',
  );
}
